2018-04-20 00:27:31,856 - unitTest - ERROR - Failed Extraction of Pmr or company
Traceback (most recent call last):
  File "/Users/srivasan/privateRepo/Travis-TestProject/test.py", line 40, in test01PmrPattern
    self.assertEqual(extractCompanyName(msg),val)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: None != '20963,669,706 S.I.G Grand Camp'
2018-04-20 00:55:48,882 - unitTest - ERROR - Failed Extraction of Pmr or company
Traceback (most recent call last):
  File "/Users/srivasan/privateRepo/Travis-TestProject/test.py", line 40, in test01PmrPattern
    self.assertEqual(extractCompanyName(msg),val)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != '20963,669,706 S.I.G Grand Camp'
2018-04-20 01:05:39,793 - unitTest - ERROR - Cannot Extract PMR ID
None
